/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.thriftgen;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class ApolloConstants {

  public static final String DEFAULT_QUORUM_STR = "127.0.0.1:2181";

  public static final String LEADER_PATH = "/apollo/leader";

  public static final Set<TaskStatus> ACTIVE_STATES = new HashSet<TaskStatus>();
  static {
    ACTIVE_STATES.add(com.apollo.thriftgen.TaskStatus.STARTING);
    ACTIVE_STATES.add(com.apollo.thriftgen.TaskStatus.RUNNING);
    ACTIVE_STATES.add(com.apollo.thriftgen.TaskStatus.KILLING);
    ACTIVE_STATES.add(com.apollo.thriftgen.TaskStatus.PURGING);
    ACTIVE_STATES.add(com.apollo.thriftgen.TaskStatus.RESTARTING);
  }

  public static final Set<TaskStatus> TERMINAL_STATES = new HashSet<TaskStatus>();
  static {
    TERMINAL_STATES.add(com.apollo.thriftgen.TaskStatus.FINISHED);
    TERMINAL_STATES.add(com.apollo.thriftgen.TaskStatus.FAILED);
    TERMINAL_STATES.add(com.apollo.thriftgen.TaskStatus.KILLED);
    TERMINAL_STATES.add(com.apollo.thriftgen.TaskStatus.LOST);
    TERMINAL_STATES.add(com.apollo.thriftgen.TaskStatus.PURGED);
    TERMINAL_STATES.add(com.apollo.thriftgen.TaskStatus.STAGING);
  }

}
