/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.thriftgen;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-03-14")
public class SchedulerVerifyTasksResult implements org.apache.thrift.TBase<SchedulerVerifyTasksResult, SchedulerVerifyTasksResult._Fields>, java.io.Serializable, Cloneable, Comparable<SchedulerVerifyTasksResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SchedulerVerifyTasksResult");

  private static final org.apache.thrift.protocol.TField VERIFIED_TASKS_FIELD_DESC = new org.apache.thrift.protocol.TField("verifiedTasks", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SchedulerVerifyTasksResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SchedulerVerifyTasksResultTupleSchemeFactory());
  }

  public List<TaskID> verifiedTasks; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VERIFIED_TASKS((short)1, "verifiedTasks");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VERIFIED_TASKS
          return VERIFIED_TASKS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VERIFIED_TASKS, new org.apache.thrift.meta_data.FieldMetaData("verifiedTasks", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TaskID.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SchedulerVerifyTasksResult.class, metaDataMap);
  }

  public SchedulerVerifyTasksResult() {
  }

  public SchedulerVerifyTasksResult(
    List<TaskID> verifiedTasks)
  {
    this();
    this.verifiedTasks = verifiedTasks;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SchedulerVerifyTasksResult(SchedulerVerifyTasksResult other) {
    if (other.isSetVerifiedTasks()) {
      List<TaskID> __this__verifiedTasks = new ArrayList<TaskID>(other.verifiedTasks.size());
      for (TaskID other_element : other.verifiedTasks) {
        __this__verifiedTasks.add(new TaskID(other_element));
      }
      this.verifiedTasks = __this__verifiedTasks;
    }
  }

  public SchedulerVerifyTasksResult deepCopy() {
    return new SchedulerVerifyTasksResult(this);
  }

  @Override
  public void clear() {
    this.verifiedTasks = null;
  }

  public int getVerifiedTasksSize() {
    return (this.verifiedTasks == null) ? 0 : this.verifiedTasks.size();
  }

  public java.util.Iterator<TaskID> getVerifiedTasksIterator() {
    return (this.verifiedTasks == null) ? null : this.verifiedTasks.iterator();
  }

  public void addToVerifiedTasks(TaskID elem) {
    if (this.verifiedTasks == null) {
      this.verifiedTasks = new ArrayList<TaskID>();
    }
    this.verifiedTasks.add(elem);
  }

  public List<TaskID> getVerifiedTasks() {
    return this.verifiedTasks;
  }

  public SchedulerVerifyTasksResult setVerifiedTasks(List<TaskID> verifiedTasks) {
    this.verifiedTasks = verifiedTasks;
    return this;
  }

  public void unsetVerifiedTasks() {
    this.verifiedTasks = null;
  }

  /** Returns true if field verifiedTasks is set (has been assigned a value) and false otherwise */
  public boolean isSetVerifiedTasks() {
    return this.verifiedTasks != null;
  }

  public void setVerifiedTasksIsSet(boolean value) {
    if (!value) {
      this.verifiedTasks = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VERIFIED_TASKS:
      if (value == null) {
        unsetVerifiedTasks();
      } else {
        setVerifiedTasks((List<TaskID>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VERIFIED_TASKS:
      return getVerifiedTasks();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VERIFIED_TASKS:
      return isSetVerifiedTasks();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SchedulerVerifyTasksResult)
      return this.equals((SchedulerVerifyTasksResult)that);
    return false;
  }

  public boolean equals(SchedulerVerifyTasksResult that) {
    if (that == null)
      return false;

    boolean this_present_verifiedTasks = true && this.isSetVerifiedTasks();
    boolean that_present_verifiedTasks = true && that.isSetVerifiedTasks();
    if (this_present_verifiedTasks || that_present_verifiedTasks) {
      if (!(this_present_verifiedTasks && that_present_verifiedTasks))
        return false;
      if (!this.verifiedTasks.equals(that.verifiedTasks))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_verifiedTasks = true && (isSetVerifiedTasks());
    list.add(present_verifiedTasks);
    if (present_verifiedTasks)
      list.add(verifiedTasks);

    return list.hashCode();
  }

  @Override
  public int compareTo(SchedulerVerifyTasksResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetVerifiedTasks()).compareTo(other.isSetVerifiedTasks());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVerifiedTasks()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.verifiedTasks, other.verifiedTasks);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SchedulerVerifyTasksResult(");
    boolean first = true;

    sb.append("verifiedTasks:");
    if (this.verifiedTasks == null) {
      sb.append("null");
    } else {
      sb.append(this.verifiedTasks);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SchedulerVerifyTasksResultStandardSchemeFactory implements SchemeFactory {
    public SchedulerVerifyTasksResultStandardScheme getScheme() {
      return new SchedulerVerifyTasksResultStandardScheme();
    }
  }

  private static class SchedulerVerifyTasksResultStandardScheme extends StandardScheme<SchedulerVerifyTasksResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SchedulerVerifyTasksResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VERIFIED_TASKS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.verifiedTasks = new ArrayList<TaskID>(_list16.size);
                TaskID _elem17;
                for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                {
                  _elem17 = new TaskID();
                  _elem17.read(iprot);
                  struct.verifiedTasks.add(_elem17);
                }
                iprot.readListEnd();
              }
              struct.setVerifiedTasksIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SchedulerVerifyTasksResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.verifiedTasks != null) {
        oprot.writeFieldBegin(VERIFIED_TASKS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.verifiedTasks.size()));
          for (TaskID _iter19 : struct.verifiedTasks)
          {
            _iter19.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SchedulerVerifyTasksResultTupleSchemeFactory implements SchemeFactory {
    public SchedulerVerifyTasksResultTupleScheme getScheme() {
      return new SchedulerVerifyTasksResultTupleScheme();
    }
  }

  private static class SchedulerVerifyTasksResultTupleScheme extends TupleScheme<SchedulerVerifyTasksResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SchedulerVerifyTasksResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetVerifiedTasks()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetVerifiedTasks()) {
        {
          oprot.writeI32(struct.verifiedTasks.size());
          for (TaskID _iter20 : struct.verifiedTasks)
          {
            _iter20.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SchedulerVerifyTasksResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.verifiedTasks = new ArrayList<TaskID>(_list21.size);
          TaskID _elem22;
          for (int _i23 = 0; _i23 < _list21.size; ++_i23)
          {
            _elem22 = new TaskID();
            _elem22.read(iprot);
            struct.verifiedTasks.add(_elem22);
          }
        }
        struct.setVerifiedTasksIsSet(true);
      }
    }
  }

}

