/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.thriftgen;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TaskStatus implements org.apache.thrift.TEnum {
  STAGING(0),
  STARTING(1),
  RUNNING(2),
  KILLING(3),
  PURGING(4),
  RESTARTING(5),
  FINISHED(6),
  FAILED(7),
  KILLED(8),
  PURGED(9),
  LOST(10);

  private final int value;

  private TaskStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TaskStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return STAGING;
      case 1:
        return STARTING;
      case 2:
        return RUNNING;
      case 3:
        return KILLING;
      case 4:
        return PURGING;
      case 5:
        return RESTARTING;
      case 6:
        return FINISHED;
      case 7:
        return FAILED;
      case 8:
        return KILLED;
      case 9:
        return PURGED;
      case 10:
        return LOST;
      default:
        return null;
    }
  }
}
