//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Apollo_ttypes = require('./Apollo_types')


var ttypes = require('./Agent_types');
//HELPER FUNCTIONS AND STRUCTURES

AgentService_ping_args = function(args) {
  this.scheduler = null;
  if (args) {
    if (args.scheduler !== undefined && args.scheduler !== null) {
      this.scheduler = new Apollo_ttypes.SchedulerID(args.scheduler);
    }
  }
};
AgentService_ping_args.prototype = {};
AgentService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.scheduler = new Apollo_ttypes.SchedulerID();
        this.scheduler.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('AgentService_ping_args');
  if (this.scheduler !== null && this.scheduler !== undefined) {
    output.writeFieldBegin('scheduler', Thrift.Type.STRUCT, 1);
    this.scheduler.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_ping_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Apollo_ttypes.Response(args.success);
    }
  }
};
AgentService_ping_result.prototype = {};
AgentService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Apollo_ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('AgentService_ping_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_getAgentHealth_args = function(args) {
  this.scheduler = null;
  if (args) {
    if (args.scheduler !== undefined && args.scheduler !== null) {
      this.scheduler = new Apollo_ttypes.SchedulerID(args.scheduler);
    }
  }
};
AgentService_getAgentHealth_args.prototype = {};
AgentService_getAgentHealth_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.scheduler = new Apollo_ttypes.SchedulerID();
        this.scheduler.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_getAgentHealth_args.prototype.write = function(output) {
  output.writeStructBegin('AgentService_getAgentHealth_args');
  if (this.scheduler !== null && this.scheduler !== undefined) {
    output.writeFieldBegin('scheduler', Thrift.Type.STRUCT, 1);
    this.scheduler.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_getAgentHealth_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Apollo_ttypes.Response(args.success);
    }
  }
};
AgentService_getAgentHealth_result.prototype = {};
AgentService_getAgentHealth_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Apollo_ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_getAgentHealth_result.prototype.write = function(output) {
  output.writeStructBegin('AgentService_getAgentHealth_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_getTaskHealth_args = function(args) {
  this.scheduler = null;
  if (args) {
    if (args.scheduler !== undefined && args.scheduler !== null) {
      this.scheduler = new Apollo_ttypes.SchedulerID(args.scheduler);
    }
  }
};
AgentService_getTaskHealth_args.prototype = {};
AgentService_getTaskHealth_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.scheduler = new Apollo_ttypes.SchedulerID();
        this.scheduler.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_getTaskHealth_args.prototype.write = function(output) {
  output.writeStructBegin('AgentService_getTaskHealth_args');
  if (this.scheduler !== null && this.scheduler !== undefined) {
    output.writeFieldBegin('scheduler', Thrift.Type.STRUCT, 1);
    this.scheduler.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_getTaskHealth_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Apollo_ttypes.Response(args.success);
    }
  }
};
AgentService_getTaskHealth_result.prototype = {};
AgentService_getTaskHealth_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Apollo_ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_getTaskHealth_result.prototype.write = function(output) {
  output.writeStructBegin('AgentService_getTaskHealth_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_registerTask_args = function(args) {
  this.scheduler = null;
  this.task = null;
  if (args) {
    if (args.scheduler !== undefined && args.scheduler !== null) {
      this.scheduler = new Apollo_ttypes.SchedulerID(args.scheduler);
    }
    if (args.task !== undefined && args.task !== null) {
      this.task = new Apollo_ttypes.TaskDescriptor(args.task);
    }
  }
};
AgentService_registerTask_args.prototype = {};
AgentService_registerTask_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.scheduler = new Apollo_ttypes.SchedulerID();
        this.scheduler.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.task = new Apollo_ttypes.TaskDescriptor();
        this.task.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_registerTask_args.prototype.write = function(output) {
  output.writeStructBegin('AgentService_registerTask_args');
  if (this.scheduler !== null && this.scheduler !== undefined) {
    output.writeFieldBegin('scheduler', Thrift.Type.STRUCT, 1);
    this.scheduler.write(output);
    output.writeFieldEnd();
  }
  if (this.task !== null && this.task !== undefined) {
    output.writeFieldBegin('task', Thrift.Type.STRUCT, 2);
    this.task.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_registerTask_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.AgentTaskRegistrationException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Apollo_ttypes.Response(args.success);
    }
    if (args.ex !== undefined && args.ex !== null) {
      this.ex = args.ex;
    }
  }
};
AgentService_registerTask_result.prototype = {};
AgentService_registerTask_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Apollo_ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.AgentTaskRegistrationException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_registerTask_result.prototype.write = function(output) {
  output.writeStructBegin('AgentService_registerTask_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_killTask_args = function(args) {
  this.scheduler = null;
  this.task = null;
  if (args) {
    if (args.scheduler !== undefined && args.scheduler !== null) {
      this.scheduler = new Apollo_ttypes.SchedulerID(args.scheduler);
    }
    if (args.task !== undefined && args.task !== null) {
      this.task = new Apollo_ttypes.TaskID(args.task);
    }
  }
};
AgentService_killTask_args.prototype = {};
AgentService_killTask_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.scheduler = new Apollo_ttypes.SchedulerID();
        this.scheduler.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.task = new Apollo_ttypes.TaskID();
        this.task.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_killTask_args.prototype.write = function(output) {
  output.writeStructBegin('AgentService_killTask_args');
  if (this.scheduler !== null && this.scheduler !== undefined) {
    output.writeFieldBegin('scheduler', Thrift.Type.STRUCT, 1);
    this.scheduler.write(output);
    output.writeFieldEnd();
  }
  if (this.task !== null && this.task !== undefined) {
    output.writeFieldBegin('task', Thrift.Type.STRUCT, 2);
    this.task.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_killTask_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.AgentTaskKillException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Apollo_ttypes.Response(args.success);
    }
    if (args.ex !== undefined && args.ex !== null) {
      this.ex = args.ex;
    }
  }
};
AgentService_killTask_result.prototype = {};
AgentService_killTask_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Apollo_ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.AgentTaskKillException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_killTask_result.prototype.write = function(output) {
  output.writeStructBegin('AgentService_killTask_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_purge_args = function(args) {
  this.scheduler = null;
  if (args) {
    if (args.scheduler !== undefined && args.scheduler !== null) {
      this.scheduler = new Apollo_ttypes.SchedulerID(args.scheduler);
    }
  }
};
AgentService_purge_args.prototype = {};
AgentService_purge_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.scheduler = new Apollo_ttypes.SchedulerID();
        this.scheduler.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_purge_args.prototype.write = function(output) {
  output.writeStructBegin('AgentService_purge_args');
  if (this.scheduler !== null && this.scheduler !== undefined) {
    output.writeFieldBegin('scheduler', Thrift.Type.STRUCT, 1);
    this.scheduler.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_purge_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.AgentTaskPurgeException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Apollo_ttypes.Response(args.success);
    }
    if (args.ex !== undefined && args.ex !== null) {
      this.ex = args.ex;
    }
  }
};
AgentService_purge_result.prototype = {};
AgentService_purge_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Apollo_ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.AgentTaskPurgeException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_purge_result.prototype.write = function(output) {
  output.writeStructBegin('AgentService_purge_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_kill_args = function(args) {
  this.scheduler = null;
  if (args) {
    if (args.scheduler !== undefined && args.scheduler !== null) {
      this.scheduler = new Apollo_ttypes.SchedulerID(args.scheduler);
    }
  }
};
AgentService_kill_args.prototype = {};
AgentService_kill_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.scheduler = new Apollo_ttypes.SchedulerID();
        this.scheduler.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_kill_args.prototype.write = function(output) {
  output.writeStructBegin('AgentService_kill_args');
  if (this.scheduler !== null && this.scheduler !== undefined) {
    output.writeFieldBegin('scheduler', Thrift.Type.STRUCT, 1);
    this.scheduler.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_kill_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Apollo_ttypes.Response(args.success);
    }
  }
};
AgentService_kill_result.prototype = {};
AgentService_kill_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Apollo_ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_kill_result.prototype.write = function(output) {
  output.writeStructBegin('AgentService_kill_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_getTaskPorts_args = function(args) {
  this.scheduler = null;
  this.task = null;
  if (args) {
    if (args.scheduler !== undefined && args.scheduler !== null) {
      this.scheduler = new Apollo_ttypes.SchedulerID(args.scheduler);
    }
    if (args.task !== undefined && args.task !== null) {
      this.task = new Apollo_ttypes.TaskID(args.task);
    }
  }
};
AgentService_getTaskPorts_args.prototype = {};
AgentService_getTaskPorts_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.scheduler = new Apollo_ttypes.SchedulerID();
        this.scheduler.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.task = new Apollo_ttypes.TaskID();
        this.task.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_getTaskPorts_args.prototype.write = function(output) {
  output.writeStructBegin('AgentService_getTaskPorts_args');
  if (this.scheduler !== null && this.scheduler !== undefined) {
    output.writeFieldBegin('scheduler', Thrift.Type.STRUCT, 1);
    this.scheduler.write(output);
    output.writeFieldEnd();
  }
  if (this.task !== null && this.task !== undefined) {
    output.writeFieldBegin('task', Thrift.Type.STRUCT, 2);
    this.task.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentService_getTaskPorts_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Apollo_ttypes.Response(args.success);
    }
  }
};
AgentService_getTaskPorts_result.prototype = {};
AgentService_getTaskPorts_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Apollo_ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentService_getTaskPorts_result.prototype.write = function(output) {
  output.writeStructBegin('AgentService_getTaskPorts_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
AgentServiceClient.prototype = {};
AgentServiceClient.prototype.seqid = function() { return this._seqid; }
AgentServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
AgentServiceClient.prototype.ping = function(scheduler, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping(scheduler);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping(scheduler);
  }
};

AgentServiceClient.prototype.send_ping = function(scheduler) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
  var args = new AgentService_ping_args();
  args.scheduler = scheduler;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentService_ping_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ping failed: unknown result');
};
AgentServiceClient.prototype.getAgentHealth = function(scheduler, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getAgentHealth(scheduler);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getAgentHealth(scheduler);
  }
};

AgentServiceClient.prototype.send_getAgentHealth = function(scheduler) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getAgentHealth', Thrift.MessageType.CALL, this.seqid());
  var args = new AgentService_getAgentHealth_args();
  args.scheduler = scheduler;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentServiceClient.prototype.recv_getAgentHealth = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentService_getAgentHealth_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getAgentHealth failed: unknown result');
};
AgentServiceClient.prototype.getTaskHealth = function(scheduler, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getTaskHealth(scheduler);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getTaskHealth(scheduler);
  }
};

AgentServiceClient.prototype.send_getTaskHealth = function(scheduler) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getTaskHealth', Thrift.MessageType.CALL, this.seqid());
  var args = new AgentService_getTaskHealth_args();
  args.scheduler = scheduler;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentServiceClient.prototype.recv_getTaskHealth = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentService_getTaskHealth_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getTaskHealth failed: unknown result');
};
AgentServiceClient.prototype.registerTask = function(scheduler, task, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_registerTask(scheduler, task);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_registerTask(scheduler, task);
  }
};

AgentServiceClient.prototype.send_registerTask = function(scheduler, task) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('registerTask', Thrift.MessageType.CALL, this.seqid());
  var args = new AgentService_registerTask_args();
  args.scheduler = scheduler;
  args.task = task;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentServiceClient.prototype.recv_registerTask = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentService_registerTask_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('registerTask failed: unknown result');
};
AgentServiceClient.prototype.killTask = function(scheduler, task, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_killTask(scheduler, task);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_killTask(scheduler, task);
  }
};

AgentServiceClient.prototype.send_killTask = function(scheduler, task) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('killTask', Thrift.MessageType.CALL, this.seqid());
  var args = new AgentService_killTask_args();
  args.scheduler = scheduler;
  args.task = task;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentServiceClient.prototype.recv_killTask = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentService_killTask_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('killTask failed: unknown result');
};
AgentServiceClient.prototype.purge = function(scheduler, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_purge(scheduler);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_purge(scheduler);
  }
};

AgentServiceClient.prototype.send_purge = function(scheduler) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('purge', Thrift.MessageType.CALL, this.seqid());
  var args = new AgentService_purge_args();
  args.scheduler = scheduler;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentServiceClient.prototype.recv_purge = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentService_purge_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('purge failed: unknown result');
};
AgentServiceClient.prototype.kill = function(scheduler, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_kill(scheduler);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_kill(scheduler);
  }
};

AgentServiceClient.prototype.send_kill = function(scheduler) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('kill', Thrift.MessageType.CALL, this.seqid());
  var args = new AgentService_kill_args();
  args.scheduler = scheduler;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentServiceClient.prototype.recv_kill = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentService_kill_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('kill failed: unknown result');
};
AgentServiceClient.prototype.getTaskPorts = function(scheduler, task, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getTaskPorts(scheduler, task);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getTaskPorts(scheduler, task);
  }
};

AgentServiceClient.prototype.send_getTaskPorts = function(scheduler, task) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getTaskPorts', Thrift.MessageType.CALL, this.seqid());
  var args = new AgentService_getTaskPorts_args();
  args.scheduler = scheduler;
  args.task = task;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentServiceClient.prototype.recv_getTaskPorts = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentService_getTaskPorts_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getTaskPorts failed: unknown result');
};
AgentServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
AgentServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

AgentServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new AgentService_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 1) {
    Q.fcall(this._handler.ping, args.scheduler)
      .then(function(result) {
        var result = new AgentService_ping_result({success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ping", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ping(args.scheduler, function (err, result) {
      if (err == null) {
        var result = new AgentService_ping_result((err != null ? err : {success: result}));
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ping", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AgentServiceProcessor.prototype.process_getAgentHealth = function(seqid, input, output) {
  var args = new AgentService_getAgentHealth_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getAgentHealth.length === 1) {
    Q.fcall(this._handler.getAgentHealth, args.scheduler)
      .then(function(result) {
        var result = new AgentService_getAgentHealth_result({success: result});
        output.writeMessageBegin("getAgentHealth", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAgentHealth", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getAgentHealth(args.scheduler, function (err, result) {
      if (err == null) {
        var result = new AgentService_getAgentHealth_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getAgentHealth", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAgentHealth", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AgentServiceProcessor.prototype.process_getTaskHealth = function(seqid, input, output) {
  var args = new AgentService_getTaskHealth_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getTaskHealth.length === 1) {
    Q.fcall(this._handler.getTaskHealth, args.scheduler)
      .then(function(result) {
        var result = new AgentService_getTaskHealth_result({success: result});
        output.writeMessageBegin("getTaskHealth", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getTaskHealth", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getTaskHealth(args.scheduler, function (err, result) {
      if (err == null) {
        var result = new AgentService_getTaskHealth_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getTaskHealth", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getTaskHealth", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AgentServiceProcessor.prototype.process_registerTask = function(seqid, input, output) {
  var args = new AgentService_registerTask_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.registerTask.length === 2) {
    Q.fcall(this._handler.registerTask, args.scheduler, args.task)
      .then(function(result) {
        var result = new AgentService_registerTask_result({success: result});
        output.writeMessageBegin("registerTask", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.AgentTaskRegistrationException) {
          var result = new AgentService_registerTask_result(err);
          output.writeMessageBegin("registerTask", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("registerTask", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.registerTask(args.scheduler, args.task, function (err, result) {
      if (err == null || err instanceof ttypes.AgentTaskRegistrationException) {
        var result = new AgentService_registerTask_result((err != null ? err : {success: result}));
        output.writeMessageBegin("registerTask", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("registerTask", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AgentServiceProcessor.prototype.process_killTask = function(seqid, input, output) {
  var args = new AgentService_killTask_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.killTask.length === 2) {
    Q.fcall(this._handler.killTask, args.scheduler, args.task)
      .then(function(result) {
        var result = new AgentService_killTask_result({success: result});
        output.writeMessageBegin("killTask", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.AgentTaskKillException) {
          var result = new AgentService_killTask_result(err);
          output.writeMessageBegin("killTask", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("killTask", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.killTask(args.scheduler, args.task, function (err, result) {
      if (err == null || err instanceof ttypes.AgentTaskKillException) {
        var result = new AgentService_killTask_result((err != null ? err : {success: result}));
        output.writeMessageBegin("killTask", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("killTask", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AgentServiceProcessor.prototype.process_purge = function(seqid, input, output) {
  var args = new AgentService_purge_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.purge.length === 1) {
    Q.fcall(this._handler.purge, args.scheduler)
      .then(function(result) {
        var result = new AgentService_purge_result({success: result});
        output.writeMessageBegin("purge", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.AgentTaskPurgeException) {
          var result = new AgentService_purge_result(err);
          output.writeMessageBegin("purge", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("purge", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.purge(args.scheduler, function (err, result) {
      if (err == null || err instanceof ttypes.AgentTaskPurgeException) {
        var result = new AgentService_purge_result((err != null ? err : {success: result}));
        output.writeMessageBegin("purge", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("purge", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AgentServiceProcessor.prototype.process_kill = function(seqid, input, output) {
  var args = new AgentService_kill_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.kill.length === 1) {
    Q.fcall(this._handler.kill, args.scheduler)
      .then(function(result) {
        var result = new AgentService_kill_result({success: result});
        output.writeMessageBegin("kill", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("kill", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.kill(args.scheduler, function (err, result) {
      if (err == null) {
        var result = new AgentService_kill_result((err != null ? err : {success: result}));
        output.writeMessageBegin("kill", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("kill", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AgentServiceProcessor.prototype.process_getTaskPorts = function(seqid, input, output) {
  var args = new AgentService_getTaskPorts_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getTaskPorts.length === 2) {
    Q.fcall(this._handler.getTaskPorts, args.scheduler, args.task)
      .then(function(result) {
        var result = new AgentService_getTaskPorts_result({success: result});
        output.writeMessageBegin("getTaskPorts", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getTaskPorts", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getTaskPorts(args.scheduler, args.task, function (err, result) {
      if (err == null) {
        var result = new AgentService_getTaskPorts_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getTaskPorts", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getTaskPorts", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

